# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2705f9d049846fd4a5ed3bcdcba53d195a1bce3cec7454edd2b5d4a08e48a97ea89b885642bb0265ed7a8fc4ed1ddcf3d963bc68f71771494323555efce04258

test:
  secret_key_base: f3a20618fbe334872b9d126d6ddbda76676e9211a524593b7a9793f3eb80b155aade05071e90e33271757edf9dcf0c4cff32241480dc455dd6b2c4185caa6f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
